apiVersion: sovereign-catalog.io/v1alpha1
kind: CompanyProfile
metadata:
  slug: "amd"
  displayName: "Advanced Micro Devices, Inc."
spec:
  jurisdiction:
    corporateHQ: "USA"
    ultimateParentCompanyHQ: "USA"
    registrationNumber: "US-AMD-0000002488"
  contact:
    website: "https://www.amd.com"
    partnerEmail: "sovereign@amd.com"
  certifications:
    - framework: "ISO-27001"
      status: "Active"
    - framework: "SOC2"
      status: "Active"
