apiVersion: sovereign-catalog.io/v1alpha1
kind: SoftwareListing
metadata:
  companyRef: "companies/ibm"
  vendor: "International Business Machines Corporation"
  product: "IBM Aspera"
  version: "4.4.3"
  lifecycleStatus: "approved"
  storefrontVisibility: "public"
spec:
  openSource:
    enabled: false
    license: "IBM International Program License Agreement"
    sourceAvailable: false
  jurisdiction:
    hq: "USA"
    ultimateParentCompanyHQ: "USA"
  architecture:
    format: "Kubernetes"
    airgapReady: true
    dependencyEndpoints: []
    storage:
      csiAccessModes: ["ReadWriteOnce"]
      volumeSnapshotSupport: true
  security:
    podSecurityStandard: "restricted"
    requiresClusterAdmin: false
    readOnlyRootFilesystem: true
    kmsIntegration: true
  deployment:
    type: "Operator"
    repository: "oci://icr.io/cpopen/aspera-hsts-operator-bundle:4.4.3"
