apiVersion: sovereign-catalog.io/v1alpha1
kind: CompanyProfile
metadata:
  slug: "open-source"
  displayName: "Open Source Community"
spec:
  jurisdiction:
    corporateHQ: "Global"
    ultimateParentCompanyHQ: "Global"
  contact:
    website: "https://opensource.org"
    partnerEmail: "info@opensource.org"
