{{- if .Values.dockerhubPullSecret.create }}
{{- $namespace := default .Release.Namespace .Values.namespaceOverride -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerhubPullSecret.secretName | quote }}
  namespace: {{ $namespace }}
  labels:
    app: {{ .Values.commonLabels.app | quote }}
    service-type: {{ index .Values.commonLabels "service-type" | quote }}
    managed-by: byop-broker
    {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%q:{"username":%q,"password":%q,"email":%q,"auth":%q}}}` .Values.dockerhubPullSecret.dockerServer .Values.dockerhubPullSecret.dockerUsername .Values.dockerhubPullSecret.dockerPassword .Values.dockerhubPullSecret.dockerEmail (printf "%s:%s" .Values.dockerhubPullSecret.dockerUsername .Values.dockerhubPullSecret.dockerPassword | b64enc) | b64enc }}
{{- end }}

# Made with Bob
